name: Python application

on:
  # Trigger the workflow manually or on push to files in src/main/resources/
  workflow_dispatch:
  schedule:
    - cron: '58 17 * * 1,4'

jobs:
  process_geeksforgeeks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet
        run: wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Process GeeksForGeeks
        run: |
          cd usernameVerifier
          python -u main.py ../src/main/resources/CMRIT2025Leaderboard.csv GeeksForGeeks

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-geeksforgeeks
          path: usernameVerifier/geeksforgeeks_debug.log
          compression-level: 9
          retention-days: 5

  process_codeforces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet
        run: wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Process Codeforces
        run: |
          cd usernameVerifier
          python -u main.py ../src/main/resources/CMRIT2025Leaderboard.csv Codeforces

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-codeforces
          path: usernameVerifier/codeforces_debug.log
          compression-level: 9
          retention-days: 5

  process_leetcode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet
        run: wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Process LeetCode
        run: |
          cd usernameVerifier
          python -u main.py ../src/main/resources/CMRIT2025Leaderboard.csv LeetCode

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-leetcode
          path: usernameVerifier/leetcode_debug.log
          compression-level: 9
          retention-days: 5

  process_codechef:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet
        run: wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Process CodeChef
        run: |
          cd usernameVerifier
          python -u main.py ../src/main/resources/CMRIT2025Leaderboard.csv CodeChef

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-codechef
          path: usernameVerifier/codechef_debug.log
          compression-level: 9
          retention-days: 5

  process_hackerrank:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet
        run: wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Process HackerRank
        run: |
          cd usernameVerifier
          python -u main.py ../src/main/resources/CMRIT2025Leaderboard.csv HackerRank

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-hackerrank
          path: usernameVerifier/hackerrank_debug.log
          compression-level: 9
          retention-days: 5

  combine_results:
    needs: [process_geeksforgeeks, process_codeforces, process_leetcode, process_codechef, process_hackerrank]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Combine results
        run: |
          cd usernameVerifier
          python -u main.py ../src/main/resources/CMRIT2025Leaderboard.csv combine

      - name: Archive generated Excel File
        uses: actions/upload-artifact@v4
        with:
          name: participant_details
          path: usernameVerifier/participant_details.csv
          compression-level: 9
          retention-days: 5
